### PR TITLE
export_fn: allow duplicate Rust fn names before rename

### PR DESCRIPTION
**Pull request by jhwgh1968**
Completes the next item on my list.

### CODE REVIEW

**Comment by schungx** [comment]
```rust
(fy, iy)
```

Hey, this is Rust.  Rhai doesn't have tuples.

**Comment by schungx** [comment]
After reading the expanded code, some suggestions:

1) You do not need to check for argument length.  This is no longer necessary.  The arguments passed to `call` is guaranteed to be the right number and right types.

    So `if args.len() != ???usize { ... }` is no longer necessary.  And there is no possibility of an error, so really `call` can just return `Dynamic`.  Also no need for the `Position` parameter.

2) I'm not sure whether there is really a need for `downcast_clone`, because replacing it can be as simple as:

```rust
let arg0 = args[0usize].read_lock::<INT>().cloned();
```

    And it'll fail when faced with a shared value as a parameter.  You'll need to replace the call with `read_lock`.

3) You can consume the parameters and therefore no need to clone them.  They are by themselves clones.

| Argument type                  | Access (`n` = argument position)      | Result                                                     |
| ------------------------------ | ------------------------------------- | ---------------------------------------------------------- |
| [Primary type][standard types] | `args[n].clone().cast::<T>()`         | Copy of value.                                             |
| Custom type                    | `args[n].read_lock::<T>().unwrap()`   | Immutable reference to value.                              |
| Custom type (consumed)         | `std::mem::take(args[n]).cast::<T>()` | The _consumed_ value.<br/>The original value becomes `()`. |
| `this` object                  | `args[0].write_lock::<T>().unwrap()`  | Mutable reference to value.                                |

```rust
let arg0 = std::mem:;take(args[0usize]).cast::<T>();
```

**Comment by jhwgh1968** [comment]
> Hey, this is Rust. Rhai doesn't have tuples.

Well that explains it! Fixed to use an array.

> After reading the expanded code, some suggestions:

Since I need to refactor things a bit of for handling `self` parameters in `impl` blocks, I will investigate those suggestions after this is in.

---

Now CI is giving me a strange error with `features sync`:

```
 error[E0277]: the trait bound `std::sync::RwLock<any::Dynamic>: std::clone::Clone` is not satisfied
##[error]   --> src/any.rs:828:40
    |
828 |                 return shared_try_take(cell)
    |                                        ^^^^ the trait `std::clone::Clone` is not implemented for `std::sync::RwLock<any::Dynamic>`
```

Could you fix that please?

**Comment by schungx** [comment]
Sorry.  Forgot to sync.  Try again.

**Comment by jhwgh1968** [comment]
Looks good!

**Comment by schungx** [comment]
Let me know when I can merge.

**Comment by jhwgh1968** [comment]
Ship it!

**Comment by schungx** [comment]
@jhwgh1968   Still a problem.  I was hoping to generate names for the functions by appending the type name to it.  For example, if I expand `i8`, `i16`, `i32`, `i64`, then it'll expand to `add_i8`, `add_i16`, `add_i32` and `add_i64`.

However, seems like in normal macros I can't this kind of string manipulation to generate function names or string literals.

It seems like using a crate like `quote` may do the trick, but I'm not sure if there is another solution without pulling in yet another crate.

**Comment by jhwgh1968** [comment]
That would be a lot of work.

Instead, please see #29.

**Pull request merged**
