### PR TITLE
Function names capturing as external variables bug

### PR DESCRIPTION
**Pull request by Eliah-Lakhin**
Prior to this fix for the following snippet:

```
|| {
  x();
}
```

`x` was interpreted as an external variable for anonymous function.

### CODE REVIEW

**Comment by schungx** [comment]
Great!  Can you add a test?

**Comment by Eliah-Lakhin** [comment]
@schungx Done.

**Comment by schungx** [comment]
Thanks.  I refactored it a little bit, because I see that function calls never need to look up the index from the variable stack, so it can be skipped regardless of closures.

Do you think I need to publish `0.18.2` to `crates.io`?

**Comment by Eliah-Lakhin** [comment]
@schungx Thank you for review and fixes!

 > Do you think I need to publish 0.18.2 to crates.io?

Well, the fix is minor, I can work from your `master` branch for a while.

**Comment by schungx** [comment]
I worry that others using the crate may find that they cannot call any function inside a closure...

From what I see, it errors out on any function call.  Does it?

**Comment by Eliah-Lakhin** [comment]
> From what I see, it errors out on any function call. Does it?

Yes, that's correct. So this one is actually fixing a critical bug, but only in case other users use anonymous functions with closure already.

 > I refactored it a little bit, because I see that function calls never need to look up the index from the variable stack, so it can be skipped regardless of closures.

I'm afraid your commit implicitly introduce a new issue that is happening in relatively rare cases. I opened a PR with a fix and a test to demonstrate the issue: https://github.com/schungx/rhai/pull/28

**Comment by schungx** [comment]
In that case, let's play around with it some more for a few more days.  When you're certain that there are no more obvious bugs, I'll push out `0.18.2`.  Just don't want other users to needlessly waste time trying to figure out that it is a bug.

BTW, how is the closures working out for you?  I see that it seems to work quite smoothly regardless of what I throw at it...

**Comment by Eliah-Lakhin** [comment]
> how is the closures working out for you? I see that it seems to work quite smoothly regardless of what I throw at it...

Yes, generally it is quite stable and the syntax is transparent. I like it. I'm encountering bugs such as the one above from time to time, but these are rare edge cases I would say.

**Pull request merged**
