### PR TITLE
Add missing pub's and refactor packages.

### PR DESCRIPTION
**Pull request by schungx**

### CODE REVIEW

**Comment by jhwgh1968** [comment]
LGTM.

**Comment by jhwgh1968** [comment]
Actually, I take that back: _the code_ LGTM.

However, since the merge commit will have a title based on the PR title -- and that is all you see in `git log` -- how about something a little more descriptive?

**Comment by schungx** [comment]
Ah.  Good point!  I always ran out of ideas to name PR's.  I guess I need to merge PR's more frequently and have smaller PR's.

**Comment by jhwgh1968** [comment]
In my mind, what makes a good PR is to have "one theme" or "one main purpose". Mine do, if you didn't notice.

If you were to look on my hard drive, you'd see that I have a bunch of different "feature branches" in various states. When they are done, I rebase them one last time, and open a PR for "that feature"/"that topic"/"that change".

Since a lot of what you're doing seems to be "refactor and cleanup packages" or "make better use of codegen", that seems to be one topic. If you're actually making improvements to the language or merging from master, that would be another topic -- even if you had to make package changes around my macros in order to merge it.

Finally, about size. If the codegen library wasn't touched and CI passes, I don't do much in-depth review at the moment. It could be +/- 2000 lines, and I wouldn't care too much.

Once I can add a couple more features to the macros -- and do one small package refactor with each one, as an example -- then I will be more interested in the way you are using them. I am hoping my features will let you eliminate some of the macros you currently have, or encourage you to arrange your code in clearer ways (which are not possible right now).

**Comment by schungx** [comment]
Ah.  Good points.  The trick seems to be open up different branches for different purposes.  Say, one for code cleanup, one for other experimentation etc.  Then use rebase before putting out a PR.

I find that the reason my PR's are all over the place is because I did some refactoring, then fixed something, then did more refactoring.  In that case, I no longer can separate the "fixed something" commit out.

Maybe I can by cherry-picking commits into a PR or something... but that's way over my head.  Having more branches seem to be the solution.

**Pull request merged**
