### PR TITLE
Create functional test for generated bulk exports

### PR DESCRIPTION
**Pull request by jhwgh1968**

### CODE REVIEW

**Comment by jhwgh1968** [comment]
That's strange. It works on nightly and beta, but not stable.

I don't know of any macro-related features in the upcoming beta... I will have to look into this.

**Comment by jhwgh1968** [comment]
Okay, it seems that `expr` and `ident` have different behavior in 1.45. Since it's better in 1.46, I won't dig into it further.

Now let's see if it passes the rest of CI.

**Comment by jhwgh1968** [comment]
This has now passed CI, and is ready for review.

What do you think, @schungx? Is this an acceptable way to do all of your bulk exports of "bulit-in" operations? I am not sure you can "meta macro" this much further, so you would probably have to write these two macros for each one.

**Comment by jhwgh1968** [comment]
Good news: I made it as generic as your original intentions. The actual generated Rust is probably uglier than you were thinking, but it should be no less efficient.

If you think it's acceptable, click the merge button!

**Comment by schungx** [comment]
This looks really close to what I need!

However, it seems to be a lot of boilerplate, since the core function may need to vary.  For example, it may have different number of arguments, of different types etc.

Is it possible to extract the wrapping boilerplate from the macro and make it more general?  Such as:

```rust

macro_rules! generate_ops {
    ($op_name:ident, $op_fn:ident, $($type_names:ident),+) => {
        pub mod $op_name {
            $(
                pub mod $type_names {
                    use rhai::plugin::*;
                    use super::super::$op_fn;
                    #[export_fn]
                                    <<< Paste in code here >>>
                }
            )*
        }
    }
}```

**Comment by jhwgh1968** [comment]
> Is it possible to extract the wrapping boilerplate from the macro and make it more general?

After trying a couple of things, my current impression is: I don't think so.

When macros accept an entire block of `paste code here`, it is _literal_. It cannot be expanded or modified by the macro itself.

For example, based on your question, I tried to create a macro you invoke like this:

```rust
generate_ops! {
    name: add,
    types: i8, i16, i32, i64,
    op: pub fn add_generic<T: std::ops::Add<Output = T>>(x: T, y: T) -> T {
        x + y
    }
}
```

That is possible to write. I could generate a bunch of `fn add_i32()` which would redirect to the generic form with `T = i32`. The problem is, that doesn't really solve anything. It would still have the same "hard coding" of return type `T` and argument count of 2.

Even if you started to parameterize pieces, you still couldn't do everything. Consider:

```rust
generate_ops! {
    name: add,
    types: i8, i16, i32, i64,
    args: x, y,
    op: pub fn add_generic<T: std::ops::Add<Output = T>>(x: T, y: T) -> T {
        x + y
    }
}
```

That parameterizes the number of arguments, but not their types. If you added the return type as an input, it would be fixed, but could not be the types you expand to. And so on, and so on.

As I recall, you currently have a bunch of macros like the current state of my branch, such as `binary_op!` and `unary_op!`. They are designed after patterns of functions -- two inputs, one output, this pattern of types -- to let you copy and paste operations for types over and over again. If there is a new pattern of call, you wrote a new macro.

All the same limitations apply here, I'm sorry to say.

**Comment by schungx** [comment]
Yes actually I don't think I mind writing different macros for different cases, just wanted to see if it is possible to reduce the amount of boilerplate.

Your example is interesting:

```rust
generate_ops! {
    name: add,
    types: i8, i16, i32, i64, u8, u16, u32, u64, f32, f64,
    op: pub fn add_generic<T: std::ops::Add<Output = T>>(x: T, y: T) -> T {
        x + y
    }
}
```

Can I also run another one like this:

```rust
generate_ops! {
    name: neg,
    types: i8, i16, i32, i64,f32, f64,
    op: pub fn neg_generic<T: std::ops::Neg<Output = T>>(x: T) -> T {
        x.neg()
    }
}
```

And another one:

```rust
generate_ops! {
    name: is_neg,
    types: i8, i16, i32, i64,f32, f64,
    op: pub fn is_neg_generic<T: Zero + PartialOrd>(x: T) -> bool {
        ...
    }
}
```

If I can, then you have already solved  my problem.

**Comment by jhwgh1968** [comment]
> Can I also run another one like this:

If you wrote a second macro, perhaps called `generate_unary_op`. The current PR should really be thought of as `generate_binary_op`, i.e. the signature must be: `fn(T, T) -> T`.

If you prefer that "struct style" syntax, and having the op embedded -- even though it is limited -- I could do that instead...

**Comment by schungx** [comment]
Now I understand you.  The signature form of the function is hard coded in the macro, it seems.

I was hoping maybe you can write a proc macro that can be more flexible...  but it doesn't really matter.  Your earlier macros will do the job just fine.  Your trick is creating multi-levels of modules to differentiate the functions by namespace instead of by name.

This I suppose is fine enough. I'll play around with it some more.

**Comment by jhwgh1968** [comment]
Thanks.

Also:

> I was hoping maybe you can write a proc macro that can be more flexible

In fairness, I will expand a little bit more on why I am reluctant to do that.

Basically, procedural macros are more powerful in behavior, but see the input the same way as basic macros do: as giant token trees. This means:

1. Structuring and highlighting all the cases where the user should get an error instead of `error: macro panicked` is a manual process. Did you notice that the "simple" change to add the `return_raw` attribute was 200 lines, 50% of which were tests? That's because I had to add a number of new error cases and messages to the core parsing of attributes. That's just simple things like, "you need to have a string here" and "you need to delete a string here".

2. There is no type inference. You can tell what seems like a "type token", but anything you want to understand about what that type _is_? That is something you must know ahead of time, assume, or calculate from a blank sheet of paper.

The idea of having the user pass in a specifically-formed list of types, and then applying them to a format string in order to generate the output? That is waaaaay more complicated than it sounds given those limitations.

**Comment by schungx** [comment]
Ah!  Makes sense!

BTW, I've tried a number of combinations of your two macros.  They seem to work well for built-in types.  However, whenever it involves a type that is imported via `use`, it always come back with `cannot find type X in this scope` or something like that.

Try it out with `type X = i64` and then put `X` as one o the types.

I guess it has something to do with macro hygene but don't know enough to be able to fix it...

**Comment by jhwgh1968** [comment]
> They seem to work well for built-in types. However, whenever it involves a type that is imported via `use`, it always come back with `cannot find type X in this scope` or something like that.

The key is, you must include an  import _at the site of use_. Remember, you are creating a module, and in Rust, modules don't inherit `use` statements from the outside.

```rust
use rhai::Engine; // <-- this will do it for the generic form, but not the macro
pub fn run_thru_engine_generic<T: std::ops::Add<Output = T>>(x: T, y: Engine) -> T {
    /* magic occurs here */
    x
}

macro_rules! generate_ops {
    ($op_name:ident, $op_fn:ident, $($type_names:ident),+) => {
        pub mod $op_name {
            $(
                pub mod $type_names {
                    use rhai::plugin::*;
                    use super::super::$op_fn;
                    use rhai::Engine; // <-- this is the extra one you need for resolution within the module
                    #[export_fn]
                    pub fn op(x: $type_names, y: Engine) -> $type_names {
                        $op_fn(x, y)
                    }
                }
            )*
        }
    }
}
```

Doing that code and cleaning things up in my `macro_unroll.rs` test case will give an error about `Clone` not being implemented -- which means it was able to resolve the type `Engine`.

**Comment by schungx** [comment]
But that doesn't help if `type_names` is the type in question...  If one of the `type_names` needs to be `use`-ed, and others doesn't...

For example, say if `type_names` is `i64, bool, MyType`.  The first two requires no `use` statements, while the third one needs `use super::super::$type_names;`.

**Comment by jhwgh1968** [comment]
> EDIT: OK. I can put in `use {i64, bool};` to import them to the root.

And if necessary, you can use the ultimate sledgehammer I used in my macros! `use super::super::*;` :smile:

**Pull request merged**
