### PR TITLE
Diagnostic improvements for Codegen Macros

### PR DESCRIPTION
**Pull request by jhwgh1968**
I duplicated all of the `#[export_fn]` diagnostic tests to use a `#[rhai_fn]` inside a module. Sure enough, it caught some things!

I also found another case of confusing errors for return types that are not `T: Clone`, and handled duplicated Rust names with special logic. (I was hoping not to do that, but the errors are extremely difficult to re-span without a lot of weird side effects.)

### CODE REVIEW

**Comment by jhwgh1968** [comment]
Oh dear. It seems I have found a bug in trybuild!

I will revert the tests which trigger the bug for now.

**Comment by jhwgh1968** [comment]
That's disappointing. But at least on my machine I can prove I have fixed the diagnostic issues you were having with return types, @schungx!

**Comment by schungx** [comment]
OK, looks good.  It seems like the general errors are picked out.

However, if you put a `#[export_module]` inside a macro itself (for types expansion maybe?), then the errors do not have span info.

It could be a limitation with macros though...

As it stands right now, it is heaps better already.

**Comment by jhwgh1968** [comment]
> However, if you put a `#[export_module]` inside a macro itself (for types expansion maybe?), then the errors do not have span info.

Hmm, that's not what I would expect. Could you put an example in #38?

**Pull request merged**
